name: Get Top PT Stream Services

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0,12,17 * * *' # At 00:00, 12:00, and 17:00 every day

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: checkout
        uses: actions/checkout@v2

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'
          
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: execute script
        env:
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          KIDS_LIST: ${{ vars.KIDS_LIST }}
          PRINT_LISTS: ${{ vars.PRINT_LISTS }}
        run: python top_pt_stream_services.py
